# Generated by Django 3.2.6 on 2021-11-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urldata',
            name='user',
            field=models.CharField(default='anon', max_length=200),
        ),
    ]
